# Generated by Django 5.2.18 on 2026-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=200)),
                ("product_desc", models.CharField(max_length=400)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=200)),
                ("stock", models.IntegerField()),
                ("popularity", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "Product",
                "managed": False,
            },
        ),
    ]
